### ISSUE TITLE
poprawić animacje gąsienic

### ISSUE THREAD

**Issue by achorostian** [CzolgIT/tanksgame#13]
animacje powinny być zależne od czasu, a nie od klatek.
zależność od czasu jest użyta przy poruszaniu się czołgu - warto tam zajrzeć.

**Comment by dz3lo** [comment]
animacje zmieniłem narazie tylko pod siebie :D bo mam większą ilość klatek.
ten błąd będzie wymagał dodania ograniczenia fps'ów w menu ustawień.

**Comment by dz3lo** [comment]
ponownie trochę to poprawiłem. teraz animacja wznawia się od miejsca zatrzymania.

**Comment by achorostian** [comment]
zrobione
