### ISSUE TITLE
Wykrywanie kolizji 

### ISSUE THREAD

**Issue by achorostian** [CzolgIT/tanksgame#2]
trzeba napisać klasę kolider , która będzie obiektem przechowującym „obrys” innych obiektów. Takie klasy później będziemy porównywać czy się na siebie nakładają (kolidują)

jeśli będzie to zbyt wolne, to warto podzielić planszę

**Comment by Matmalecki** [comment]
https://gamedev.stackexchange.com/questions/39931/fast-accurate-2d-collision

**Comment by Matmalecki** [comment]
Wstępnie działające schemat colliderów już jest, teraz czekam na sprite ściany żeby dopasować, a teraz pracuję nad uwzględnieniem w kolizji kąta nachylenia czołgu

**Comment by dz3lo** [comment]
ok, działają kolizje na obróconych prostokątach (by @Matmalecki )
następny krok to najprawdopodobniej ślizganie się po napotkaniu ściany

**Comment by Matmalecki** [comment]
Zrobione w 80 % , ale póki co wystarczy do testów.
