### ISSUE TITLE
Fix libpng warnings

### ISSUE THREAD

**Issue by inql** [CzolgIT/tanksgame#20]
While running, the output on console is like below:
`libpng warning: iCCP: known incorrect sRGB profile`
`libpng warning: iCCP: cHRM chunk does not match sRGB`

:-1: :-1: 

(jestem rakiem)

**Comment by inql** [comment]
https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile

need to test that solution, that might be a problem with certain files

@Matmalecki @OskarBir - check that, since @dz3lo cannot reproduce the problem

**Comment by dz3lo** [comment]
przekonwertowalem pliki png z sRGB do RGB w gimpie. Błąd nadal występuje?

**Comment by Matmalecki** [comment]
Błąd nie wystepuje już od dawna, zamykam.
