### ISSUE TITLE
Zamienić wpisywane na sztywno liczby na zmienne globalne

### ISSUE THREAD

**Issue by Matmalecki** [CzolgIT/tanksgame#21]

**Comment by dz3lo** [comment]
prędkość czołgu i obrotu zmieniona

**Comment by dz3lo** [comment]
plik konfiguracyjny przejął ważne "systemowe" zmienne globalne.
reszta zmiennych odpowiadających np za prędkości i skale pojedynczych obiektów zostaje w Main.h
ścieżki do plików graficznych zostały przeniesione do TextureManager'a
