### ISSUE TITLE
czy dodać warstwy rysowania? czy może sortować listę gameobjectów?

### ISSUE THREAD

**Issue by achorostian** [CzolgIT/tanksgame#23]
czolg musi byc rysowany ostatni... nwm jak to rozegrac
narazie rysuje sie dwa razy
```
    for (int i = 0; i < gameObjects.size();i++)
    {
      gameObjects[i]->draw( x0 , y0 );
    }
    player->draw( x0 , y0 ); 
```

**Comment by Matmalecki** [comment]
Najlepiej by było zrobić funkcję sortującą na podstawie typu.

**Comment by dz3lo** [comment]
sortowanie spowolni grę. chyba lepiej byłoby nadać np trzy rangi i zrobić trzy pętle rysujące (ilość rang w zależności od potrzeb)

**Comment by achorostian** [comment]
zostały zrobione osobne listy do:
- pocisków
- czołgów
- animacji
- obiektów mapy (gameObjects)
