### ISSUE TITLE
Lepsza pętla do sprawdzania kolizji między obiektami

### ISSUE THREAD

**Issue by Matmalecki** [CzolgIT/tanksgame#25]
Trzeba uwzględnić dużą liczbę możliwości co z czym może kolidować. Również można pomijać możiwości kolizji pomiędzy niektórymi obiektami.

**Comment by dz3lo** [comment]
dodałem ograniczenie, aby sprawdzane były tylko elementy:
* dynamiczne + statyczne
* dynamiczne + dynamiczne
* tylko w odległości od siebie (licząc od środka) mniejszej lub równej od sumy połów ich przekątnych

**Comment by achorostian** [comment]
done
