### ISSUE TITLE
Rysowanie tekstur tła tylko potrzebnych + klasa kamery

### ISSUE THREAD

**Issue by achorostian** [CzolgIT/tanksgame#5]
w klasie: Background

Każda teksturka tła (na razie) ma rozmiar 512x512. Chodzi o to, żeby tekstury nie były drukowane na całej mapie w ciemno, tylko żeby były renderowane w aktualnym oknie – tylko tyle ile trzeba

**Comment by dz3lo** [comment]
obecną kamerę-widok (nie klasę) przesunąłem na faktyczny środek. jest lepiej.

**Comment by achorostian** [comment]
dodane skalowanie gry. Teraz każdy może widzieć trochę inny obszar, więc kamera byłaby dość skomplikowana do napisania. Wydajnośc nam wzrosła więc rezygnujemy z tej funkcji
